"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { displayBroker, displayStrategy, displayValue } from "@/lib/display";

export type ConnectionSummary = { public_id: string; label?: string; broker_name?: string; server: string; environment: string; enabled: boolean; account_count: number; last_verified_at?: string; is_default: boolean };
export type ProfileSummary = { public_id: string; name: string; account_alias: string; execution_mode: string; strategy_name: string; strategy_version: string; enabled: boolean; autonomous_armed?:boolean; armed_until?:string; autonomous_shadow_mode?:boolean; decision_provider?:string; minimum_confidence?:number; risk?: { risk_per_trade_percent?: number; maximum_open_positions?: number } };
export type AccountSummary = { public_id: string; account_alias: string; account_name?: string; broker_name?: string; currency?: string; environment: string; is_demo?: number | null; available: boolean; locally_enabled: boolean; is_default_analysis: boolean; connection_id: string; profiles: ProfileSummary[] };
export type ScheduleSummary = { id:string;profile_ref:string;timezone:string;expression:{times:string[]};enabled:boolean;next_run_at?:string;next_run_at_local?:string;last_run_at?:string;last_run_at_local?:string;last_run_status?:string;maximum_lateness_seconds:number;latest_dispatch?:{id:string;state:string;safe_retry:boolean;reason_code?:string;outcome?:string} };
export type WorkerHealth = { status:string;workers:Array<{worker_id:string;status:string;last_heartbeat_at:string;healthy:boolean}> };
export type DailySummary = { date:string;outcomes:{TRADE:number;NO_TRADE:number;BLOCKED:number;ERROR:number};daily_entry_count:number;kill_switch:boolean;armed_profiles:number };

export default function AccountsPanel({ connections, accounts, executions, schedules, workerHealth, dailySummary }: { connections: ConnectionSummary[]; accounts: AccountSummary[]; profiles: ProfileSummary[]; executions:Array<{id:string;action_type:string;state:string;created_at:string}>; schedules:ScheduleSummary[]; workerHealth:WorkerHealth; dailySummary:DailySummary }) {
  const router = useRouter(); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState(""); const [profileStatus,setProfileStatus]=useState<Record<string,string>>({});
  async function mutate(path:string,method="PUT",body?:object){setBusy(path);setError("");const response=await fetch(`/api/backend/${path}`,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});if(!response.ok)setError(String((await response.json().catch(()=>({}))).detail??"Unable to update TradeLocker. Try again or reauthenticate."));else router.refresh();setBusy(null);}
  function rename(account:AccountSummary){const alias=window.prompt("New account alias",account.account_alias)?.trim();if(alias&&alias!==account.account_alias)void mutate(`broker/accounts/${account.public_id}/alias`,"PUT",{alias});}
  function createProfile(account:AccountSummary){const name=window.prompt(`Profile name\n\nAccount: ${account.account_alias}\nBroker: ${displayBroker(account.broker_name)}\nEnvironment: ${displayValue(account.environment)}\nStrategy: Hourly Forex v1\nExecution Mode: Read Only`,`${account.account_alias} Hourly`)?.trim();if(name&&window.confirm(`Create “${name}” for ${account.account_alias} in Read Only mode?`))void mutate("execution-profiles","POST",{name,account_id:account.public_id,execution_mode:"read_only"});}
  function editProfile(account:AccountSummary,profile:ProfileSummary){const requested=window.prompt(`Execution mode for ${profile.name}\nEnter read_only${account.is_demo===1?" or demo_manual":""}.\nDemo Autonomous is unavailable.`,profile.execution_mode)?.trim();const allowed=account.is_demo===1?["read_only","demo_manual"]:["read_only"];if(requested&&allowed.includes(requested)&&window.confirm(`Save ${profile.name}\nAccount: ${account.account_alias}\nBroker: ${displayBroker(account.broker_name)}\nEnvironment: ${displayValue(account.environment)}\nStrategy: ${displayStrategy(profile.strategy_name,profile.strategy_version)}\nExecution Mode: ${displayValue(requested)}?`))void mutate(`execution-profiles/${profile.public_id}`,"PUT",{execution_mode:requested});}
  function armProfile(account:AccountSummary,profile:ProfileSummary){const shadow=window.confirm(`SAFE DEFAULT: run ${profile.name} in Shadow Mode?\n\nOK = decisions and previews only; no order submission.\nCancel = continue to a separate auto-submit warning.`);if(!shadow&&!window.confirm(`AUTO-SUBMIT WARNING\n\nArm verified DEMO account ${account.account_alias} for autonomous order submission for up to 24 hours?\n\nRisk: ${profile.risk?.risk_per_trade_percent??0.25}% per trade\nMaximum entries: 2/day\nMaximum position/order: 1 each\nDaily loss: 3%\nDrawdown cutoff: 10%\nCooldown after loss: 60 minutes\nLive and weekend execution remain blocked.`))return;const provider=(window.prompt("Decision provider: openai or no_trade","openai")||"").trim();if(!["openai","no_trade"].includes(provider))return;if(window.confirm(`Confirm Demo Autonomy\n\nProfile: ${profile.name}\nAccount: ${account.account_alias}\nEnvironment: DEMO ONLY\nProvider: ${provider}\nMode: ${shadow?"Shadow (no submission)":"Auto-submit after deterministic validation"}\nExpires automatically in 24 hours\n\nThe global kill switch remains authoritative.`))void mutate(`execution-profiles/${profile.public_id}/autonomy/arm`,"POST",{arming_hours:24,decision_provider:provider,minimum_confidence:0.7,allowed_sessions:["london","new_york","overlap"],shadow_mode:shadow});}
  function configureSchedule(profile:ProfileSummary){const current=schedules.find(item=>item.profile_ref===profile.public_id);const entered=window.prompt(`Daily America/Chicago run times for ${profile.name} (comma-separated HH:MM)`,current?.expression.times.join(",")||"05:00,07:00,09:00,11:00,13:15")?.trim();if(!entered)return;const local_times=entered.split(",").map(item=>item.trim()).filter(Boolean);if(window.confirm(`Save ${local_times.join(", ")} America/Chicago for ${profile.name}?\n\nThe schedule cannot arm the profile or bypass the kill switch.`))void mutate(`execution-profiles/${profile.public_id}/autonomy/schedule`,"POST",{timezone:"America/Chicago",local_times,enabled:true,maximum_lateness_seconds:600});}
  async function checkStatus(profile:ProfileSummary){setProfileStatus(current=>({...current,[profile.public_id]:"Checking…"}));const autonomous=profile.execution_mode==="demo_autonomous"||profile.autonomous_armed;const response=await fetch(`/api/backend/execution-profiles/${profile.public_id}/${autonomous?"autonomy/status":"demo-status"}`);const body=await response.json().catch(()=>({}));setProfileStatus(current=>({...current,[profile.public_id]:response.ok?((autonomous?body.status==="ready":body.ready_for_preview)?"Ready":`Blocked: ${(body.blocking_reasons??[]).join(", ")}`):"Status Unavailable"}));}
  if(!connections.length)return <section className="management-section"><div className="section-heading"><div><div className="eyebrow">TradeLocker Connections</div><h2>No TradeLocker connections are configured.</h2></div><a className="button" href="/connect-tradelocker?new=1">Add Connection</a></div></section>;
  return <section className="management-section"><div className="section-heading"><div><div className="eyebrow">TradeLocker Connections</div><h2>Connections, Accounts, and Execution Profiles</h2><p>Manage every stored account. The Default Account is used only for general requests without an alias or profile.</p></div><a className="button" href="/connect-tradelocker?new=1">Add Connection</a></div>{error&&<div className="error">{error} <button className="button secondary" onClick={()=>router.refresh()}>Try Again</button></div>}<div className="connection-list">{connections.map(connection=>{const owned=accounts.filter(account=>account.connection_id===connection.public_id);return <article className="card connection-card" key={connection.public_id}>
    <header className="connection-header"><div><h3>{connection.label||displayBroker(connection.broker_name||connection.server)}</h3><p>{displayBroker(connection.broker_name||connection.server)}</p></div><div className="badges"><span className="status">{displayValue(connection.environment)}</span><span className="status">{connection.enabled?"Connected":"Reauthentication Required"}</span>{connection.is_default&&<span className="status">Default Connection</span>}</div></header>
    <div className="metadata"><span>Last verified: {connection.last_verified_at?new Date(connection.last_verified_at).toLocaleString():"Not yet verified"}</span><span>Account count: {owned.length}</span></div>{!connection.enabled&&<div className="notice">This connection could not refresh. Reauthenticate to restore account access.</div>}
    <div className="actions compact"><button className="button secondary" disabled={Boolean(busy)} onClick={()=>void mutate(`broker/tradelocker/discover-accounts?connection_id=${encodeURIComponent(connection.public_id)}`,"POST")}>Refresh Accounts</button><a className="button secondary" href={`/connect-tradelocker?connection_id=${encodeURIComponent(connection.public_id)}`}>Reauthenticate</a><a className="button secondary" href={`/connect-tradelocker?connection_id=${encodeURIComponent(connection.public_id)}`}>Update Credentials</a></div><details className="technical"><summary>Technical Details</summary><code>{connection.public_id}</code></details>
    <div className="account-stack">{owned.length?owned.map(account=><article className="account-card" key={account.public_id}><header className="account-header"><div><h4>{account.account_alias}</h4><p>{account.account_name||`${displayBroker(account.broker_name)} Account`}</p></div><div className="badges"><span className="status">{account.is_demo===1?"Demo":account.is_demo===0?"Live":"Unknown"}</span><span className="status">{account.available&&account.locally_enabled?"Active":"Unavailable"}</span>{account.is_default_analysis&&<span className="status">Default Account</span>}</div></header><div className="metadata"><span>Currency: {account.currency||"Unknown"}</span></div>{account.is_default_analysis&&<p className="helper">Used for general account requests when no account alias or execution profile is specified. Other accounts remain available.</p>}<details className="technical"><summary>Technical Details</summary><div>Account reference: <code>{account.public_id}</code></div></details>
      <div className="profile-list"><div className="label">Execution Profiles</div>{account.profiles.length?account.profiles.map(profile=><div className="profile-row" key={profile.public_id}><div><strong>{profile.name}</strong><small>{displayStrategy(profile.strategy_name,profile.strategy_version)} · {displayValue(profile.execution_mode)} · {profile.enabled?"Enabled":"Disabled"}</small><small>Risk per trade: {profile.risk?.risk_per_trade_percent??0.25}% · Maximum open positions: {profile.risk?.maximum_open_positions??1}</small>{profile.autonomous_armed&&<small>Demo Autonomy armed until {profile.armed_until?new Date(profile.armed_until).toLocaleString():"expiry unavailable"} · {profile.autonomous_shadow_mode?"Shadow Mode":"Auto-submit"} · {profile.decision_provider}</small>}{profileStatus[profile.public_id]&&<small>{profileStatus[profile.public_id]}</small>}</div><div className="actions compact"><button className="button secondary" onClick={()=>void checkStatus(profile)}>Check Execution Status</button>{account.is_demo===1&&<button className="button secondary" onClick={()=>configureSchedule(profile)}>Schedule</button>}{account.is_demo===1&&(profile.autonomous_armed?<button className="button danger" onClick={()=>window.confirm(`Disarm Demo Autonomy for ${profile.name}?`)&&void mutate(`execution-profiles/${profile.public_id}/autonomy/disarm`,"POST")}>Disarm Autonomy</button>:<button className="button" onClick={()=>armProfile(account,profile)}>Arm Demo Autonomy</button>)}<button className="button secondary" onClick={()=>editProfile(account,profile)}>Edit Profile</button><button className="button secondary" onClick={()=>void mutate(`execution-profiles/${profile.public_id}`,"PUT",{enabled:!profile.enabled})}>{profile.enabled?"Disable Profile":"Enable Profile"}</button><button className="button danger" onClick={()=>window.confirm(`Delete profile “${profile.name}”?`)&&void mutate(`execution-profiles/${profile.public_id}`,"DELETE")}>Delete Profile</button></div></div>):<p>No execution profiles are attached to this account.</p>}</div>
      <div className="actions compact"><button className="button" onClick={()=>createProfile(account)}>Create Profile</button><button className="button secondary" onClick={()=>rename(account)}>Rename Alias</button>{!account.is_default_analysis&&<button className="button secondary" onClick={()=>void mutate(`broker/accounts/${account.public_id}/default`)}>Make Default Account</button>}<span className="destructive-spacer"/>{account.locally_enabled&&<button className="button danger" onClick={()=>window.confirm(`Disable account ${account.account_alias}?`)&&void mutate(`broker/accounts/${account.public_id}/disable`)}>Disable Account</button>}</div></article>):<div className="notice">No accounts have been discovered for this connection. Refresh the connection or reauthenticate if the credentials have expired.</div>}</div>
    <div className="destructive-zone">{connection.enabled&&<button className="button danger" onClick={()=>window.confirm(`Disable connection ${connection.label||connection.server}?`)&&void mutate(`broker/connections/${connection.public_id}/disable`)}>Disable Connection</button>}</div></article>})}</div>
    <article className="card" style={{marginTop:20}}><div className="label">Autonomous Scheduler</div><p>Worker: <strong>{displayValue(workerHealth.status)}</strong> · Kill switch: <strong>{dailySummary.kill_switch?"Enabled":"Disabled"}</strong></p><p>Today UTC — TRADE {dailySummary.outcomes.TRADE} · NO TRADE {dailySummary.outcomes.NO_TRADE} · BLOCKED {dailySummary.outcomes.BLOCKED} · ERROR {dailySummary.outcomes.ERROR} · Actual entries {dailySummary.daily_entry_count}</p>{schedules.length?schedules.map(schedule=><div className="profile-row" key={schedule.id}><div><strong>{accounts.flatMap(item=>item.profiles).find(item=>item.public_id===schedule.profile_ref)?.name||schedule.profile_ref}</strong><small>{schedule.expression.times.join(", ")} {schedule.timezone}</small><small>Next local: {schedule.next_run_at_local?new Date(schedule.next_run_at_local).toLocaleString():"Paused"} · UTC: {schedule.next_run_at?new Date(schedule.next_run_at).toISOString():"Paused"}</small><small>Last: {schedule.last_run_status?`${displayValue(schedule.last_run_status)} at ${schedule.last_run_at_local?new Date(schedule.last_run_at_local).toLocaleString():"unknown"}`:"No run yet"}{schedule.latest_dispatch?.reason_code?` · ${displayValue(schedule.latest_dispatch.reason_code)}`:""}</small></div><div className="actions compact"><button className="button secondary" onClick={()=>void mutate(`autonomous-schedules/${schedule.id}/${schedule.enabled?"pause":"resume"}`,"POST")}>{schedule.enabled?"Pause":"Resume"}</button>{schedule.latest_dispatch?.safe_retry&&["retry_exhausted","error"].includes(schedule.latest_dispatch.state)&&<button className="button secondary" onClick={()=>window.confirm("Retry this safe pre-submit failure with the same run key?")&&void mutate(`autonomous-schedule-runs/${schedule.latest_dispatch?.id}/retry`,"POST")}>Retry Safe Failure</button>}<button className="button danger" onClick={()=>window.confirm("Delete this autonomous schedule?")&&void mutate(`autonomous-schedules/${schedule.id}`,"DELETE")}>Delete</button></div></div>):<p>No autonomous schedules are configured.</p>}<div className="actions compact"><button className="button danger" onClick={()=>window.confirm("Enable the global kill switch and block all new entries?")&&void mutate("operations/kill-switch/enable","POST")}>Enable Kill Switch</button></div></article>
    <article className="card" style={{marginTop:20}}><div className="label">Recent Demo Executions</div>{executions.length?executions.map(item=><p key={item.id}><strong>{displayValue(item.action_type)}</strong> · {displayValue(item.state)} · {new Date(item.created_at).toLocaleString()}</p>):<p>No demo executions have been recorded.</p>}</article></section>;
}
